server:
  port: 8070
spring:
  application.name: reservationservice
  profiles.active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/reservations
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
  data.web.pageable.one-indexed-parameters: true
management:
  endpoint:
    health.probes.enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure.include: info,health,loggers
