spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratings
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update