name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - gateway
          - libraryservice
          - reservationservice
          - ratingservice
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "21"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x ${{ matrix.project }}/gradlew

      - name: Build ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: ./gradlew build

      - name: Upload artifact ${{ matrix.project }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.project }}-jar
          path: ${{ matrix.project }}/build/libs/*.jar
          retention-days: 1
          
      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      # - name: Build project
      #   uses: eskatos/gradle-command-action@v2
      #   with:
      #     arguments: clean build
  grade:
    name: Autograding
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - uses: actions/download-artifact@v3
        with:
          name: gateway-jar
          path: gateway/build/libs/

      - uses: actions/download-artifact@v3
        with:
          name: libraryservice-jar
          path: libraryservice/build/libs/

      - uses: actions/download-artifact@v3
        with:
          name: reservationservice-jar
          path: reservationservice/build/libs/

      - uses: actions/download-artifact@v3
        with:
          name: ratingservice-jar
          path: ratingservice/build/libs/


      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up --wait
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v